version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

  chroma:
    image: chromadb/chroma
    container_name: chroma-db
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - chroma-data:/chroma/.chroma/index

volumes:
  redis-data:
  chroma-data: